// AUTO-GENERATED by scripts/fetch_cert_pins.ps1
// Generated: 2026-08-26 13:11:24
// DO NOT EDIT MANUALLY - run scripts/build_release.ps1 to regenerate

class CertPins {
  CertPins._();

  /// SHA-256 SPKI fingerprints for pinned domains (base64-encoded)
  static const Map<String, List<String>> pins = {
    'firestore.googleapis.com': ['RCAp94bQ1oMwwP/gHk2NBDhQ12j7ODOcTsk9+okENZw='],
    'identitytoolkit.googleapis.com': ['ASTzMxJiYPPXwXhqoVxZGM5J+5SmSziLL4OqopXA5R8='],
    'firebase.googleapis.com': ['ASTzMxJiYPPXwXhqoVxZGM5J+5SmSziLL4OqopXA5R8='],
    'api.paystack.co': ['+KoXgd5R6ehjfU0t4F+oJRA5QmUKedICs0z0PX4PbHY='],
    'api.twilio.com': ['NGIODiyXgzyHTNTvMHU3D8wpPljLJ2nr0Frp1hBT4gU='],
  };

  /// Pinned hosts for quick lookup
  static final Set<String> pinnedHosts = pins.keys.toSet();
}
