// AUTO-GENERATED by scripts/fetch_cert_pins.ps1
// Generated: 2026-08-28 14:35:13
// DO NOT EDIT MANUALLY - run scripts/build_release.ps1 to regenerate

class CertPins {
  CertPins._();

  /// SHA-256 SPKI fingerprints for pinned domains (base64-encoded)
  static const Map<String, List<String>> pins = {
    'firestore.googleapis.com': ['3LI7icEixXdr9hDdSnm7azsoozR8bdrRxjeXcjbC1RM='],
    'identitytoolkit.googleapis.com': ['47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='],
    'firebase.googleapis.com': ['n99lOdRhIS7cbDQhf2+D8CzzKYdWBq3Wc2/Bh7jCWzw='],
    'api.paystack.co': ['+KoXgd5R6ehjfU0t4F+oJRA5QmUKedICs0z0PX4PbHY='],
    'api.twilio.com': ['NGIODiyXgzyHTNTvMHU3D8wpPljLJ2nr0Frp1hBT4gU='],
  };

  /// Pinned hosts for quick lookup
  static final Set<String> pinnedHosts = pins.keys.toSet();
}
